theme:
  name: "material"
  language: ru

site_name: GarpixCMS
repo_url: https://github.com/garpixcms/garpixcms

plugins:
  - search
  - mkdocstrings
  - i18n:
      default_language: ru
      languages:
        en: 'English'
        ru: 'Russian'
      nav_translations:
        en:
          Установка: Install
          Примеры: Examples
          Пакеты: Packages
          Миграция кода: Migrations 
          Устаревшие статьи: Old

nav:
  - index.md
  - Установка:
    - install_deps.md
    - install_new_project.md
    - install_start_project.md
  - Примеры:
    - examples/simple_templates_site.md
    - examples/auth_spa.md
    - examples/auth_templates.md
    - Social authentication:
      - Apple ID: examples/auth/apple.md
      - Google: examples/auth/google.md
    - examples/notify.md
  - Пакеты:
    - packages/packages.md
    - packages/garpix_notify.md
    - packages/garpix_page.md
    - packages/garpix_menu.md
    - packages/garpix_auth.md
    - packages/garpix_user.md
    - packages/garpix_qa.md
    - packages/garpix_company.md
    - packages/utils.md
  # - Утилиты: utils.md
  - FAQ:
    - CORS: faq_cors.md
    - Создание своего пакета: faq_pack.md
    - Количество выводимых записей в Структуре страниц: faq_list_per_page.md
  - Миграция кода:
    - 1.15.0 -> 2.0.0: migrate/migrate_1.15.0_to_2.0.0.md
  - Устаревшие статьи:
    - Простой корпорат на шаблонах (устарел 10.09.2021): deprecated/example_simple_templates_site_deprecated_2021-09-10.md
